export interface FundHolding {
  tickerCode?: string;
  unlistedSlug?: string;
  targetName: string;
  enTargetName?: string;
  category: 'listed' | 'unlisted';
  ownershipRatioPct: number;
  holdingShares?: string;
  enHoldingShares?: string;
  estimatedValueBillion: number;
  filingDate: string;
  purpose: string;
  enPurpose?: string;
  status: 'increasing' | 'holding' | 'decreasing' | 'lead_investor';
}

export interface InvestorFund {
  id: string;
  slug: string;
  name: string;
  enName: string;
  shortName: string;
  enShortName: string;
  type: 'activist' | 'vc' | 'institutional' | 'buffett';
  typeLabel: string;
  enTypeLabel: string;
  badgeColor: string;
  country: string;
  enCountry: string;
  headquarters: string;
  enHeadquarters: string;
  representative: string;
  enRepresentative: string;
  establishedYear: number;
  aumTrillionYen: number;
  aumLabel: string;
  enAumLabel: string;
  description: string;
  enDescription: string;
  strategy: string;
  enStrategy: string;
  officialWebsiteUrl: string;
  topHoldings: FundHolding[];
}

export const INVESTOR_FUNDS_DATA: InvestorFund[] = [
  // 1. 🔥 エリオット・マネジメント (Elliott Management)
  {
    id: 'elliott',
    slug: 'elliott',
    name: 'エリオット・マネジメント (Elliott Investment Management)',
    enName: 'Elliott Investment Management L.P.',
    shortName: 'エリオット',
    enShortName: 'Elliott',
    type: 'activist',
    typeLabel: '物言う株主 (アクティビスト)',
    enTypeLabel: 'Activist / Value Unlock',
    badgeColor: 'bg-rose-50 text-rose-700 border-rose-200',
    country: '米国 (フロリダ/NY)',
    enCountry: 'USA (Florida / New York)',
    headquarters: '米国フロリダ州ウェストパームビーチ',
    enHeadquarters: 'West Palm Beach, FL, USA',
    representative: 'ポール・シンガー (Paul Singer)',
    enRepresentative: 'Paul Singer',
    establishedYear: 1977,
    aumTrillionYen: 10.5,
    aumLabel: '約10.5兆円 ($70B+)',
    enAumLabel: '¥10.5T ($70B+)',
    description: '運用資産10兆円超を誇る世界屈指のヘッジファンド・アクティビスト。徹底的な財務・資産分析に基づき、保有不動産の流動化、政策保有株の売却、大規模自社株買い、コングロマリット・ディスカウントの解消を企業に強く要求する。',
    enDescription: 'One of the world’s most prominent activist hedge funds with over $70B in AUM. Demands monetization of hidden real estate, cross-shareholding unwind, large-scale buybacks, and dismantling of conglomerate discounts.',
    strategy: '隠れた資産価値（都心不動産や遊休資産）を持つ大企業にターゲットを絞り、経営陣への直接対話と書簡公表で株主価値向上を迫る。',
    enStrategy: 'Targets undervalued conglomerates with prime urban assets; unlocks massive shareholder value via direct boardroom engagement and public letters.',
    officialWebsiteUrl: 'https://elliottmgmt.com/',
    topHoldings: [
      {
        tickerCode: '8801',
        targetName: '三井不動産',
        enTargetName: 'Mitsui Fudosan Co., Ltd.',
        category: 'listed',
        ownershipRatioPct: 2.8,
        holdingShares: '26,500,000株',
        enHoldingShares: '26.5M shares',
        estimatedValueBillion: 1550,
        filingDate: '2024年2月',
        purpose: '大規模自社株買い（1兆円規模）およびオリエンタルランド（OLC）保有株式の売却・資本効率改善要求',
        enPurpose: 'Demanded ¥1T share buyback, divestment of Oriental Land (Tokyo Disney) stake, and ROE optimization.',
        status: 'holding',
      },
      {
        tickerCode: '6758',
        targetName: 'ソニーグループ',
        enTargetName: 'Sony Group Corporation',
        category: 'listed',
        ownershipRatioPct: 1.5,
        holdingShares: '18,800,000株',
        enHoldingShares: '18.8M shares',
        estimatedValueBillion: 2400,
        filingDate: '2020年',
        purpose: '半導体（CMOSイメージセンサー）部門の分社化および金融子会社（ソニーフィナンシャル）完全分離要求',
        enPurpose: 'Proposed spinoff of semiconductor (CMOS sensor) division and separation of financial services.',
        status: 'holding',
      },
      {
        tickerCode: '7203',
        targetName: 'トヨタ自動車 (系列部品株)',
        enTargetName: 'Toyota Motor Group (Affiliates)',
        category: 'listed',
        ownershipRatioPct: 3.1,
        holdingShares: '保有開示',
        enHoldingShares: 'Disclosed stake',
        estimatedValueBillion: 850,
        filingDate: '2023年',
        purpose: 'トヨタグループ親子上場解消および政策保有株式の相互解消要求',
        enPurpose: 'Advocated for unwinding of cross-shareholdings and parent-subsidiary governance cleanup.',
        status: 'holding',
      },
    ],
  },

  // 2. 🦅 バークシャー・ハサウェイ (Berkshire Hathaway) - バフェットの日本株巨額投資
  {
    id: 'berkshire-hathaway',
    slug: 'berkshire-hathaway',
    name: 'バークシャー・ハサウェイ (Berkshire Hathaway - Warren Buffett)',
    enName: 'Berkshire Hathaway Inc. (Warren Buffett)',
    shortName: 'バフェット (バークシャー)',
    enShortName: 'Berkshire (Buffett)',
    type: 'buffett',
    typeLabel: 'バフェット・長期バリュー投資',
    enTypeLabel: 'Buffett / Ultra Long-Term Value',
    badgeColor: 'bg-amber-50 text-amber-700 border-amber-200',
    country: '米国 (ネブラスカ州オマハ)',
    enCountry: 'USA (Omaha, Nebraska)',
    headquarters: '米国ネブラスカ州オマハ',
    enHeadquarters: 'Omaha, NE, USA',
    representative: 'ウォーレン・バフェット (Warren Buffett)',
    enRepresentative: 'Warren Buffett',
    establishedYear: 1965,
    aumTrillionYen: 150.0,
    aumLabel: '約150兆円 ($1T+)',
    enAumLabel: '¥150T ($1.0T+)',
    description: '「投資の神様」ウォーレン・バフェット率いる世界最大の投資持株会社。2020年8月に日本の大手総合商社5社の株式を各5%超取得したことを電撃発表し、その後継続的に買い増しを行い各社約9%超を保有する。',
    enDescription: 'World’s premier investment holding conglomerate led by Warren Buffett. In Aug 2020, announced massive stakes across Japan’s 5 major Sogo Shosha, subsequently boosting holdings to >9.0% each.',
    strategy: '高配当・高ROE・強固なキャッシュフロー・割安なバリュエーションを誇る総合商社を永久保有前提で投資。円建て社債を発行して為替リスクを完全ヘッジ。',
    enStrategy: 'Permanent holding of cash-generative, shareholder-friendly Japanese trading giants financed via yen-denominated bonds to completely eliminate currency risk.',
    officialWebsiteUrl: 'https://www.berkshirehathaway.com/',
    topHoldings: [
      {
        tickerCode: '8058',
        targetName: '三菱商事',
        enTargetName: 'Mitsubishi Corporation',
        category: 'listed',
        ownershipRatioPct: 9.7,
        holdingShares: '138,000,000株',
        enHoldingShares: '138.0M shares',
        estimatedValueBillion: 4200,
        filingDate: '2024年3月',
        purpose: '長期投資（バリュー投資 ＆ グローバル資源・エネルギー・DX協業）',
        enPurpose: 'Ultra long-term investment, dividend compounding & global resource collaboration.',
        status: 'increasing',
      },
      {
        tickerCode: '8001',
        targetName: '伊藤忠商事',
        enTargetName: 'ITOCHU Corporation',
        category: 'listed',
        ownershipRatioPct: 9.3,
        holdingShares: '147,000,000株',
        enHoldingShares: '147.0M shares',
        estimatedValueBillion: 3900,
        filingDate: '2024年3月',
        purpose: '長期投資（非資源No.1商社、強固なリテール・生活消費基盤）',
        enPurpose: 'Core long-term holding; unmatched consumer & non-resource cash flow strengths.',
        status: 'increasing',
      },
      {
        tickerCode: '8031',
        targetName: '三井物産',
        enTargetName: 'Mitsui & Co., Ltd.',
        category: 'listed',
        ownershipRatioPct: 9.5,
        holdingShares: '146,000,000株',
        enHoldingShares: '146.0M shares',
        estimatedValueBillion: 3800,
        filingDate: '2024年3月',
        purpose: '長期投資（資源・LNG・エネルギーにおける圧倒的競争力）',
        enPurpose: 'Strategic holding in global LNG, infrastructure, and energy transition.',
        status: 'increasing',
      },
    ],
  },

  // 3. 🌴 オアシス・マネジメント (Oasis Management)
  {
    id: 'oasis',
    slug: 'oasis',
    name: 'オアシス・マネジメント (Oasis Management Company)',
    enName: 'Oasis Management Company Ltd.',
    shortName: 'オアシス',
    enShortName: 'Oasis',
    type: 'activist',
    typeLabel: '物言う株主 (アクティビスト)',
    enTypeLabel: 'Activist / Governance Reform',
    badgeColor: 'bg-rose-50 text-rose-700 border-rose-200',
    country: '香港 / ケイマン',
    enCountry: 'Hong Kong / Cayman Islands',
    headquarters: '香港 中環 (Central, Hong Kong)',
    enHeadquarters: 'Central, Hong Kong',
    representative: 'セス・フィッシャー (Seth Fischer)',
    enRepresentative: 'Seth Fischer',
    establishedYear: 2002,
    aumTrillionYen: 1.2,
    aumLabel: '約1.2兆円 ($8B)',
    enAumLabel: '¥1.2T ($8B)',
    description: '香港を拠点とするアジア特化型アクティビストファンド。小林製薬の紅麹問題における取締役選任要求、ツルハホールディングス、東京ドーム、クスリのアオキ等、日本の流通・小売・消費財企業で数々の企業統治改革を実現。',
    enDescription: 'Premier Asia-focused activist hedge fund founded by Seth Fischer. Pioneered corporate governance campaigns across Japanese retail, pharmaceuticals (Kobayashi Pharma), and drugstore consolidations.',
    strategy: 'コーポレートガバナンス（社外取締役の増員、創業家支配の是正、業界再編）を軸に株主提案を積極的に展開。',
    enStrategy: 'Drives shareholder proposals focusing on boardroom independence, elimination of founder entrenchment, and M&A consolidation.',
    officialWebsiteUrl: 'https://oasiscm.com/',
    topHoldings: [
      {
        tickerCode: '4967',
        targetName: '小林製薬',
        enTargetName: 'Kobayashi Pharmaceutical Co., Ltd.',
        category: 'listed',
        ownershipRatioPct: 5.2,
        holdingShares: '4,050,000株',
        enHoldingShares: '4.05M shares',
        estimatedValueBillion: 240,
        filingDate: '2024年6月',
        purpose: 'ガバナンス刷新、社外取締役主導による品質管理・経営体制の抜本的再構築要求',
        enPurpose: 'Demanded governance overhaul, board reconstitution, and structural quality control reforms.',
        status: 'increasing',
      },
      {
        tickerCode: '8214',
        targetName: 'AOKIホールディングス',
        enTargetName: 'AOKI Holdings Inc.',
        category: 'listed',
        ownershipRatioPct: 8.5,
        holdingShares: '7,400,000株',
        enHoldingShares: '7.4M shares',
        estimatedValueBillion: 110,
        filingDate: '2023年',
        purpose: '配当性向100%要求、ネットカフェ（快活CLUB）事業の価値最大化',
        enPurpose: 'Pushed for 100% dividend payout ratio and unlocking Kaikatsu CLUB entertainment value.',
        status: 'holding',
      },
    ],
  },

  // 4. 🦄 ソフトバンク・ビジョン・ファンド (SoftBank Vision Fund)
  {
    id: 'vision-fund',
    slug: 'vision-fund',
    name: 'ソフトバンク・ビジョン・ファンド (SoftBank Vision Fund 1 & 2)',
    enName: 'SoftBank Vision Fund (SVF 1 & 2)',
    shortName: 'ビジョンファンド (孫正義)',
    enShortName: 'Vision Fund (SVF)',
    type: 'vc',
    typeLabel: 'グローバル巨大テックVC',
    enTypeLabel: 'Global Mega Tech VC',
    badgeColor: 'bg-purple-50 text-purple-700 border-purple-200',
    country: '英国 (ロンドン) / 日本 / 米国',
    enCountry: 'UK (London) / Japan / USA',
    headquarters: '英国ロンドン メイフェア',
    enHeadquarters: 'Mayfair, London, UK',
    representative: '孫正義 (Masayoshi Son)',
    enRepresentative: 'Masayoshi Son',
    establishedYear: 2017,
    aumTrillionYen: 22.0,
    aumLabel: '約22兆円 ($150B+)',
    enAumLabel: '¥22T ($150B+)',
    description: '孫正義が立ち上げた人類史上最大のテクノロジー投資ファンド（SVF1: $100B, SVF2: $50B+）。AI、ロボティクス、自動運転、フィンテック、生成AI領域のグローバル覇権企業および日本の有力AIスタートアップに巨額投資を実行。',
    enDescription: 'The largest technology investment vehicle in history ($150B+ combined), led by Masayoshi Son. Focuses aggressively on Artificial Super Intelligence (ASI), robotics, autonomous mobility, and AI unicorns.',
    strategy: '「AI群戦略」。各分野のNo.1テック企業に対し100億円〜数千億円規模の成長資金を一気に供給し、圧倒的市場シェアを確立させる。',
    enStrategy: 'AI Cluster Strategy: Deploys mega-rounds ($100M-$1B+) into sector-defining category leaders to consolidate global dominant market share.',
    officialWebsiteUrl: 'https://visionfund.com/',
    topHoldings: [
      {
        unlistedSlug: 'pfn',
        targetName: 'Preferred Networks',
        enTargetName: 'Preferred Networks, Inc. (PFN)',
        category: 'unlisted',
        ownershipRatioPct: 8.5,
        holdingShares: 'シリーズ出資',
        enHoldingShares: 'Growth Equity',
        estimatedValueBillion: 300,
        filingDate: '2021年',
        purpose: '深層学習・AI専用半導体（MN-Core）および生成AI基盤モデル共同開発',
        enPurpose: 'Strategic growth investment in AI accelerator silicon (MN-Core) and foundation models.',
        status: 'lead_investor',
      },
      {
        unlistedSlug: 'spiber',
        targetName: 'Spiber',
        enTargetName: 'Spiber Inc. (Brewed Protein)',
        category: 'unlisted',
        ownershipRatioPct: 6.2,
        holdingShares: 'シリーズ出資',
        enHoldingShares: 'Growth Equity',
        estimatedValueBillion: 120,
        filingDate: '2022年',
        purpose: '次世代構造タンパク質素材（Brewed Protein）のグローバル商業生産加速',
        enPurpose: 'Global scaling of structural brewed protein biomaterial commercial facilities.',
        status: 'holding',
      },
    ],
  },

  // 5. 🦄 ジャフコ グループ (JAFCO Group) - 日本最大手VC
  {
    id: 'jafco',
    slug: 'jafco',
    name: 'ジャフコ グループ (JAFCO Group Co., Ltd.)',
    enName: 'JAFCO Group Co., Ltd.',
    shortName: 'ジャフコ (JAFCO)',
    enShortName: 'JAFCO',
    type: 'vc',
    typeLabel: '国内最大手ベンチャーキャピタル',
    enTypeLabel: 'Japan #1 Venture Capital',
    badgeColor: 'bg-purple-50 text-purple-700 border-purple-200',
    country: '日本 (東京・大手町)',
    enCountry: 'Japan (Tokyo Otemachi)',
    headquarters: '東京都千代田区大手町一丁目',
    enHeadquarters: 'Otemachi, Chiyoda-ku, Tokyo',
    representative: '三好啓介 (Keisuke Miyoshi)',
    enRepresentative: 'Keisuke Miyoshi',
    establishedYear: 1973,
    aumTrillionYen: 0.5,
    aumLabel: '約5,000億円',
    enAumLabel: '¥500B ($3.3B)',
    description: '1973年創業、累計IPO社数1,000社超を誇る日本VCのパイオニア。シード・アーリーからレイターまで、SmartHR、LayerX、マネーフォワードなど日本の名だたるメガベンチャーを初期から発掘・育成。',
    enDescription: 'Japan’s premier venture capital pioneer since 1973, backing over 1,000 IPOs including SmartHR, LayerX, and Money Forward from seed/early stage.',
    strategy: '伴走型ハンズオン支援。創業初期のリード投資から上場後の資本政策までを一貫してリードする。',
    enStrategy: 'Hands-on lead venture investing from seed rounds to IPO and beyond.',
    officialWebsiteUrl: 'https://www.jafco.co.jp/',
    topHoldings: [
      {
        unlistedSlug: 'smarthr',
        targetName: 'SmartHR',
        enTargetName: 'SmartHR, Inc.',
        category: 'unlisted',
        ownershipRatioPct: 12.4,
        holdingShares: '初期リード出資',
        enHoldingShares: 'Early Lead Investor',
        estimatedValueBillion: 210,
        filingDate: '2019年〜',
        purpose: '労務クラウドからエンタープライズSaaSへの事業拡大をハンズオン支援',
        enPurpose: 'Lead venture funding and hands-on governance support for cloud HR scale-up.',
        status: 'lead_investor',
      },
      {
        unlistedSlug: 'layerx',
        targetName: 'LayerX',
        enTargetName: 'LayerX Inc. (Bakuraku)',
        category: 'unlisted',
        ownershipRatioPct: 9.8,
        holdingShares: 'シリーズ出資',
        enHoldingShares: 'Series Lead',
        estimatedValueBillion: 95,
        filingDate: '2021年〜',
        purpose: '支出管理SaaS「バクラク」およびAI・Fintech事業の急成長をリード',
        enPurpose: 'Strategic lead funding for Bakuraku AI-driven enterprise spend management.',
        status: 'lead_investor',
      },
    ],
  },

  // 6. 🏛️ ブラックロック (BlackRock) - 世界最大の資産運用会社
  {
    id: 'blackrock',
    slug: 'blackrock',
    name: 'ブラックロック (BlackRock, Inc. / BlackRock Japan)',
    enName: 'BlackRock, Inc. / BlackRock Japan',
    shortName: 'ブラックロック',
    enShortName: 'BlackRock',
    type: 'institutional',
    typeLabel: '世界最大 資産運用会社 (メガ機関投資家)',
    enTypeLabel: 'World #1 Asset Manager / Mega Institutional',
    badgeColor: 'bg-indigo-50 text-indigo-700 border-indigo-200',
    country: '米国 (NY) / 日本',
    enCountry: 'USA (New York) / Japan',
    headquarters: '米国ニューヨーク州ニューヨーク',
    enHeadquarters: 'Hudson Yards, New York, NY, USA',
    representative: 'ラリー・フィンク (Larry Fink)',
    enRepresentative: 'Larry Fink',
    establishedYear: 1988,
    aumTrillionYen: 1600.0,
    aumLabel: '約1,600兆円 ($10.5T)',
    enAumLabel: '¥1,600T ($10.5T)',
    description: '運用資産10兆ドル（約1,600兆円）を誇る世界最大の資産運用会社。iShares ETFを通じて東証プライム上場企業のほぼ全社において5%前後の大株主として名を連ねる世界経済の心臓部。',
    enDescription: 'The world’s largest asset manager with $10.5T in AUM. Through its iShares ETFs and institutional index accounts, holds significant ~5% stakes across virtually every TSE Prime blue-chip.',
    strategy: 'パッシブETF運用および長期エンゲージメント。ESG、気候変動開示、取締役会の多様性と実効性を重視した議決権行使を実施。',
    enStrategy: 'Global index stewardship and long-term engagement focused on sustainability, ESG disclosure, and board effectiveness.',
    officialWebsiteUrl: 'https://www.blackrock.com/',
    topHoldings: [
      {
        tickerCode: '7203',
        targetName: 'トヨタ自動車',
        enTargetName: 'Toyota Motor Corporation',
        category: 'listed',
        ownershipRatioPct: 5.1,
        holdingShares: '685,000,000株',
        enHoldingShares: '685.0M shares',
        estimatedValueBillion: 21500,
        filingDate: '大量保有報告書',
        enPurpose: 'Index tracking and stewardship proxy voting',
        purpose: 'インデックス運用および議決権行使を通じた企業価値向上エンゲージメント',
        status: 'holding',
      },
      {
        tickerCode: '6861',
        targetName: 'キーエンス',
        enTargetName: 'Keyence Corporation',
        category: 'listed',
        ownershipRatioPct: 5.6,
        holdingShares: '13,600,000株',
        enHoldingShares: '13.6M shares',
        estimatedValueBillion: 9200,
        filingDate: '大量保有報告書',
        purpose: 'インデックス運用および機関投資家保有',
        enPurpose: 'Institutional portfolio holding & index tracking',
        status: 'holding',
      },
      {
        tickerCode: '9983',
        targetName: 'ファーストリテイリング',
        enTargetName: 'Fast Retailing Co., Ltd.',
        category: 'listed',
        ownershipRatioPct: 4.8,
        holdingShares: '15,300,000株',
        enHoldingShares: '15.3M shares',
        estimatedValueBillion: 7100,
        filingDate: '大量保有報告書',
        purpose: 'インデックス運用およびグローバル成長投資',
        enPurpose: 'Global consumer growth & index replication',
        status: 'holding',
      },
    ],
  },
];